### ISSUE TITLE
Upload broken on Chrome with Elm in version 4.0.4 of cypress-file-upload

### ISSUE THREAD

**Issue by yonigibbs** [abramenal/cypress-file-upload#181]
Hey @abramenal, remember issue #138 which you fixed a while back? It seems it's been reintroduced, but only on Chrome and Electron from what I can see (works fine on FireFox - haven't tried Edge). I've updated the repository I created for the original issue, and added a new branch, where you can see the issue: https://github.com/yonigibbs/elm-drag-drop-cypress/tree/cypress-file-upload-4.0.4. The instructions remain the same in terms of where to put the breakpoint, etc. And the root cause looks like it might be the same too: wrong constructors being used.

Thanks!

**Comment by abramenal** [comment]
Hi @yonigibbs 

Right now I am not able to take a look into the issue properly.
In the meantime, please use v3 where it was fixed.
Sorry about that. Not sure I can provide ETA on solving this issue in v4 since I am the only one contributor and maintainer. If you have ideas on fixing that, please feel free to open Pull Request and we can review it together.

Thanks for understanding.

**Comment by jdcl32** [comment]
it seems this can be solved by: https://github.com/abramenal/cypress-file-upload/pull/184

**Comment by yonigibbs** [comment]
Hey @abramenal, that's no problem at all. Totally understand, and no rush at from my point of view. Looks like there's a PR already submitted for this (thanks @jdcl32!) so I'm happy to hang off till hopefully this can be merged at some point.  Thanks!

**Comment by abramenal** [comment]
@yonigibbs can you please check whether it is fixed in `v4.0.5`?

**Comment by yonigibbs** [comment]
Unfortunately it seems like the new version doesn't resolve this issue, at least on my system. I'm on Ubuntu 18.0.4 with Chrome 81. The repo I linked at the top can be used to demonstrate this (just update the dependency from 4.0.4 to 4.0.5).  Sorry :-(

**Comment by jdcl32** [comment]
@yonigibbs I see were the issue is and is easily fixed see this PR for the fix: https://github.com/abramenal/cypress-file-upload/pull/187

**Comment by abramenal** [comment]
just release with `v4.0.6`

**Comment by yonigibbs** [comment]
Excellent! Just tested with the new v4.0.6 release from yesterday and can confirm it now works.

Thanks very much @jdcl32 and @abramenal!
